name: arc_up
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    sensors: any
    gradient_app_bar: ^0.0.1
    cupertino_icons: ^0.1.2
    tuple: any
    simple_animations: any

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: "^0.7.3"

flutter_icons:
    image_path_android: "assets/logo/icon.png"
    image_path_ios: "assets/logo/icon.png"
    android: true # can specify file name here e.g. "ic_launcher"
    ios: true # can specify file name here e.g. "My-Launcher-Icon"

# The following section is specific to Flutter.
flutter:
    fonts:
        -   family: Raleway
            fonts:
                -   asset: assets/fonts/Raleway-100.ttf
                    weight: 100
                -   asset: assets/fonts/Raleway-100i.ttf
                    weight: 100
                    style: italic
                -   asset: assets/fonts/Raleway-200.ttf
                    weight: 200
                -   asset: assets/fonts/Raleway-200i.ttf
                    weight: 200
                    style: italic
                -   asset: assets/fonts/Raleway-300.ttf
                    weight: 300
                -   asset: assets/fonts/Raleway-300i.ttf
                    weight: 300
                    style: italic
                -   asset: assets/fonts/Raleway-400.ttf
                    weight: 400
                -   asset: assets/fonts/Raleway-400i.ttf
                    weight: 400
                    style: italic
                -   asset: assets/fonts/Raleway-500.ttf
                    weight: 500
                -   asset: assets/fonts/Raleway-500i.ttf
                    weight: 500
                    style: italic
                -   asset: assets/fonts/Raleway-600.ttf
                    weight: 600
                -   asset: assets/fonts/Raleway-600i.ttf
                    weight: 600
                    style: italic
                -   asset: assets/fonts/Raleway-700.ttf
                    weight: 700
                -   asset: assets/fonts/Raleway-700i.ttf
                    weight: 700
                    style: italic
                -   asset: assets/fonts/Raleway-800.ttf
                    weight: 800
                -   asset: assets/fonts/Raleway-800i.ttf
                    weight: 800
                    style: italic
                -   asset: assets/fonts/Raleway-900.ttf
                    weight: 900
                -   asset: assets/fonts/Raleway-900i.ttf
                    weight: 900
                    style: italic
    uses-material-design: true

