class CardList {
    static const List<List<String>> list = [
        [
            'Liste',
            'Algoritma',
            'Dizi',
            'Int',
            'Double',
            'Long long',
            'While',
            'For',
            'Değişken',
            'Fonksiyon',
            'Veri Türü',
            'Döngü',
            'If',
            'Else',
            'Else if',
            'String',
            'Error',
            'Kod',
            'Derleyici',
            'Main',
            'Java',
            'C++',
            'Python',
            'HTML',
            'CSS',
            'JS',
            'Programlama Dili',
            'IDE',
            'Encoder',
            'Kamera',
            'Görüntü İşleme',
            'LED Halkasi',
            'İvmeölçer',
            'Jirometre',
            'Potansiyometre',
            'Girdi',
            'Çıktı',
            'Terminal',
            'Kütüphane',
            'CPU',
            'GPU',
            'RAM',
            'Bellek',
            'Monitör',
            'Modem',
            'Yardımcı İşlemci',
            'Git',
            'Bulut',
            'Otonom',
            'Teleop',
        ],
        [
            'Civata',
            'Somun',
            'Tekerlek',
            'Tornavida',
            'Matkap',
            'Mil',
            'Rulman',
            'Profil',
            'Alüminyum',
            'Segmen',
            'Kamera',
            'Motor',
            'Çark',
            'Çark sistemi',
            'Lastik',
            'Makara',
            'İp',
            'Limit switch',
            'Motor controller',
            'Akü',
            'Kablo',
            'Wi-Fi alıcısı',
            'Power distribution board',
            'Zincir',
            'Chainbreaker',
            'Plaka',
            'Plexi Board',
            'CAN bağlantısı',
            'Kablo soyucu',
            'Pense',
            'Kargaburun',
            'Falçata',
            'Çivi',
            'Çekiç',
            'Bumper',
            'Koli bantı',
            'Havya',
            'Lehim Teli',
            'Menteşe',
            'Çelik',
            'Tahta',
            'Çelik tel',
            'WD-40',
            'Metal',
            'Torna Makinesi',
            'Tork',
            'Hız',
            'İvme',
            'Sürtünme',
            'Solidworks',
        
        ],
    ];
    
    static const List<String> type = [
        "sample type 1",
        "sample type 2",
        "sample type 3",
    ];
}