class CardList {
    static const List<List<String>> list = [
        [
            'Liste',
            'Algoritma',
            'Dizi',
            'Int',
            'Double',
            'Long long',
            'While',
            'For',
            'Değişken',
            'Fonksiyon',
            'Veri Türü',
            'Döngü',
            'If',
            'Else',
            'Else if',
            'String',
            'Error',
            'Kod',
            'Derleyici',
            'Main',
            'Java',
            'C++',
            'Python',
            'HTML',
            'CSS',
            'JS',
            'Programlama Dili',
            'IDE',
            'Encoder',
            'Kamera',
            'Görüntü İşleme',
            'LED Halkasi',
            'İvmeölçer',
            'Jirometre',
            'Potansiyometre',
            'Girdi',
            'Çıktı',
            'Terminal',
            'Kütüphane',
            'CPU',
            'GPU',
            'RAM',
            'Bellek',
            'Monitör',
            'Modem',
            'Yardımcı İşlemci',
            'Git',
            'Bulut',
            'Otonom',
            'Teleop',
        ],
        [
            'Civata',
            'Somun',
            'Tekerlek',
            'Tornavida',
            'Matkap',
            'Mil',
            'Rulman',
            'Profil',
            'Alüminyum',
            'Segmen',
            'Kamera',
            'Motor',
            'Çark',
            'Çark sistemi',
            'Lastik',
            'Makara',
            'İp',
            'Limit switch',
            'Motor controller',
            'Akü',
            'Kablo',
            'Wi-Fi alıcısı',
            'Power distribution board',
            'Zincir',
            'Chainbreaker',
            'Plaka',
            'Plexi Board',
            'CAN bağlantısı',
            'Kablo soyucu',
            'Pense',
            'Kargaburun',
            'Falçata',
            'Çivi',
            'Çekiç',
            'Bumper',
            'Koli bantı',
            'Havya',
            'Lehim Teli',
            'Menteşe',
            'Çelik',
            'Tahta',
            'Çelik tel',
            'WD-40',
            'Metal',
            'Torna Makinesi',
            'Tork',
            'Hız',
            'İvme',
            'Sürtünme',
            'Solidworks',
        
        ],
    ];
    
    static const List<String> type = [
        "Programlama",
        "Mekanik",
    ];
    static const Map<String, String> exp = {
        'Civata': ' İki yüzeyi birbirine bağlamaya yarayan silindirik, vidaya benzeyen parça',
        'Somun': ' Civataları yerinde tutmak için yuvarlak delikli pul tarzı parça',
        'Tekerlek': ' Sürtünmeyi azaltan, robotlarin ilerlemesine yarayan daire şeklinde parça',
        'Tornavida': ' Vidayı sıkmaya yarayan alet',
        'Matkap': ' Yüksek rotasyonel hızlarda dönen, genellikle vidalamakta kullanılan araç',
        'Mil': ' İnce uzun, çarkların üstüne takıldığı metal (çoğunlukla çelik) parça',
        'Rulman': ' Millerin bağlandığı bölgede özgürce dönmesi gerektiğinde kullanılan parça',
        'Profil': ' Dikdörtgen prizma şeklinde metal (genellikle alüminyum) parça',
        'Alüminyum': ' Metal türlerinden birisi',
        'Segmen': ' Çarkları milin üstüne sabitlemekte kullanılır',
        'Kamera': ' İçine aldığı ışığı sensörler aracılığıyla sanal ortama aktaran araç',
        'Motor': ' Tekerleklerin bağlı olduğu, hızlıca dönen çok yönlü parça',
        'Çark': ' Üstünde bir sürü dişleri olan dairesel parça',
        'Çark sistemi': ' Birçok çarkın bir araya gelmesiyle oluşur',
        'Lastik': ' Elastik, çekildikçe uzayan cisim',
        'Makara': ' Güç aktarımında yön değişikliği sağlayan, sürtünmesi az olan dairesel parça',
        'İp': ' Gücü aktarmakta kullanılan, farklı kalınlıklarda bulunan ve çoğunlukla fiber yapıya sahip cisim',
        'Limit switch': ' Üstündeki anahtara basıldığında sinyal ileten parça',
        'Motor controller': ' Motorları kontrol etmeyi sağlayan elektronik ekipman',
        'Akü': ' Elektronik güç deposu',
        'Kablo': ' Bir sinyali belirli bir yere iletmek için kullanılan ince, silindirik elektronik ekipman',
        'Wi-Fi alıcısı': ' Robotun bilgisayarla kablosuz bağlantısını sağlayan parça',
        'Power distribution board': ' Aküden alınan gücü robotun bütün elektronik parçalarına dağıtan ekipman',
        'Zincir': ' Tane tane parçaların tekrarlı bir biçimde bir araya gelip kısa mesafeler arası bir bölgeden başka bir bölgeye dairesel hareket iletmeye yarayan dayanıklı parça',
        'Chainbreaker': ' Zincirleri kırmaya (kısaltıp uzunluğunu ayarlamaya) yarayan alet.',
        'Plaka': ' İnce tabaka',
        'Plexi Board': ' Şeffaf plastik plaka',
        'CAN bağlantısı': ' Motor controllerlari birbirine ve PDP’ye bağlamaya yarayan sarı-yeşil kablo',
        'Kablo soyucu': ' Kablo kesmeye ve ucunu açmaya yarayan el aleti',
        'Pense': ' Sıkmaya yarayan el aleti',
        'Kargaburun': ' Pensenin ince uzun burunlu hali',
        'Falçata': ' İçine geçen ve dışarıya çıkarılabilen bıçak',
        'Çivi': ' Ucu sivri, ince uzun, tahtaya bir parça sabitlemeye yarayan cisim',
        'Çekiç': ' Çivi çakmaya yarayan el aleti',
        'Bumper': ' Robotu dış darbelere karşı koruyan yumuşak katman',
        'Koli bantı': ' Şeffaf yapışkan bant',
        'Havya': ' Elektronik parçaları devre kartına sabitlemek için kullanılan ve ısıyla çalışan el aleti',
        'Lehim Teli': ' Kabloları devre kartına bağlamaya yarayan ve kolayca eriyen metal',
        'Menteşe': ' Belirli bir sabit nokta etrafında hareket eden iki düzlem',
        'Çelik': ' Dayanıklı ama bir o kadar da ağır alasim turu',
        'Tahta': ' Ağaçtan elde edilen malzeme',
        'Çelik tel': ' İp tarzinda, güçlü bir alaşımdan üretilen cisim',
        'WD-40': ' Sürtünmeyi azaltmak için hareketli parçalara uygulanan sıvı yağ',
        'Metal': ' Robotun yapım malzemelerinin çoğuna verilen genel isim',
        'Torna Makinesi': ' Parçalara şekil vermek için kullanılan büyük tezgah',
        'Tork': ' Kuvvet x uzaklık',
        'Hız': ' Kat edilen mesafe/zaman',
        'İvme': ' Hızın zamanla değişim miktarı',
        'Sürtünme': ' Mükemmel olmayan sistemlerde iki yüzey arası ortaya çıkan enerji kaybı',
        'Solidworks': ' Robot dizayn etmekte kullanılan yazılım',
        'Liste': ' Kullanıcılara sıralanmış bir dizi hazırlama olanağı sunar',
        'Algoritma': ' Bir bilgisayar programının bir sorunu çözmek için gerçekleştireceği işlemler ve bu işlemleri gerçekleştirme sırası',
        'Dizi': ' Aynı tipte birden çok değişkeni tutabilen veri yapıları',
        'Int': ' Milyardan küçük tam sayıları temsil eden veri türü',
        'Double': ' Ondalıklı sayıları temsil etmeye yarayan veri türü',
        'Long long': ' Milyardan büyük tam sayıları temsil etmek için kullanılan veri türü',
        'While': ' Dur denilene kadar bir işlem dizisini tekrar tekrar gerçekleştirmek için kullanılan döngü türü',
        'For': ' Bir sayım yapılırken bir işlem dizisini tekrarlamak ve o sayının değerlerini kullanırken işe yarayan döngü türü',
        'Değişken': ' Bilgisayarda sayılar ve yazılar gibi verileri saklamaya yarayan ifade',
        'Fonksiyon': ' Çeşitli değer listelerine göre değişen bir şekilde bazı işlemleri gerçekleştirebilen çeşitli yerlerde işlem dizisi',
        'Veri Türü': ' Küçük ve büyük tam sayılar, kesirli sayılar, doğru/yanlış, karakter, yazı gibi verilerin bilgisayarda hızlı temsiline yarayan veri kategorileri',
        'Döngü': ' Bir işlem dizisinin tekrar tekrar işlenmesi',
        'If': ' ifadeyi denetleyerek, ifadenin değerine göre uygun yollardan bir tanesiyle dallanma işlemini gerçekleştiren" bir kontrol deyimidir',
        'Else': ' If ile belirtilen ifade doğru değilse gerçekleştirilen kontrol deyimidir',
        'Else if': ' If ile belirtilen ifade yerine kullanılabilecek bir kontrol deyimidir',
        'String': ' String sınıfı Java\'da metinler tanımlamak için kullanılır ve bize metinler üzerinde çeşitli işlemler gerçekleştirmemiz için yardımcı fonksiyonlar sunar',
        'Error': ' Programda bir hata çıkması sonucu programın işlenişinin durma durumu',
        'Kod': ' Kod yazma veya geliştirme, bir yazılımı sıfırdan oluşturarak meydana getirme yada bir yazılımı geliştirmek için o yazılıma ekstradan kod dizgileri eklemek anlamına '
          'gelir',
        'Derleyici': ' Bir programın kodunu, bilgisayarın çalıştırabileceği hâle getiren program',
        'Main': ' Bir programın bilgisayar tarafından işlenmesine başlanılan, bir programın ana fonksiyonu',
        'Java': ' Yazılma kolaylığı ve çok sayıda platformda kullanılabilirliği ile bilinen, dünyanın en popüler programlama dillerinden biri',
        'C++': ' 1979 yılında Bjarne Stroustrup tarafından Bell Labs’da geliştirilen nesne yönelimli ve yüksek seviyeli, genel maksatlı programlama dilidir',
        'Python': ' Genellikle yazılması ve derlemesi en kolay dil kabul edilen, popülerliği her yıl gitgide artan bir programlama dili',
        'HTML': ' İnternet sayfalarının yazılarının ve bölümlerinin oluşturulmasında kullanılan dil',
        'CSS': ' İnternet sayfalarının renk, boyut gibi estetik özelliklerinin oluşturulmasında kullanılan dil',
        'JS': ' Genellikle Web’de kullanılan ama başka kullanım alanları da olan bir programlama dili',
        'Programlama Dili': ' Bilgisayarın anlayabileceği veya bilgisayarın anlayabileceği türden bir şeye çevrilebilen komutlar ve kurallar bütünü',
        'IDE': ' Hem içinde kod yazılabilen, hem de yazılan kodu çalıştırabilen yazılım',
        'Encoder': ' Robotun hareketini saptamaya yarayan sensör',
        'Görüntü İşleme': ' Kamera ile elde edilen görsel verilerin işlenmesi Buna örnek olarak bir görüntüde bir objenin konumunu ve hızını belirlemek verilebilir',
        'LED Halkası': ' LED lambaları ile sarılmış çember',
        'İvmeölçer': ' Robotun ne kadar hızlı hızlandığını ölçen sensör',
        'Jirometre': ' Robotun yönünü ve o yöndeki hızını ölçen sensör',
        'Potansiyometre': ' Kontrol edilebilen direnç',
        'Girdi': ' Bir programa işlenmesi için verilen veri',
        'Çıktı': ' Bir programın çalışması sonucu verdiği veri',
        'Terminal': ' Bilgisayar ile doğrudan etkileşim kurulabilen alan',
        'Kütüphane': ' Başka insanların yazdığı ve kendi yazdığınız kodda kullanabileceğiniz fonksiyonlar ve komutlar',
        'CPU': ' Bilgisayarın “beynidir”, bilgisayarın işlem yapabilmesini sağlar',
        'GPU': ' Özel olarak grafikleri işler, grafik işlemlerini normal bir CPU’dan daha hızlı yapar',
        'RAM': ' Bilgisayarın geçici olarak programı ve program verilerini sakladığı depo',
        'Bellek': ' Bilgisayardaki bütün kalıcı verileri saklayan depolama alanı',
        'Monitör': ' Bilgisayarın görsel olarak kullanıcıya çıktı verebilmesini sağlar',
        'Modem': ' Robot ile bilgisayar arasındaki iletişimi sağlayan aygıt',
        'Yardımcı İşlemci': ' Performansın arttırılması için kullanılır',
        'Git': ' Bir ya da birden fazla insanın üzerinde çalıştıkları bir programlama projesini bulut üzerinde tutan ve bir proje üzerinde birlikte çalışmayı kolaylaştıran bir '
          'sistemdir',
        'Bulut': ' Verilerin yerel olarak saklanması yerine internet üzerinden erişilebilir bir yerde saklandığı yer',
        'Otonom': ' Dışarıdan bir kontrol olmadan robotun gereken şeyleri gerçekleştirmesi',
        'Teleop': ' Robotun uzaktan bir insan tarafından kontrol',
    };
}
/*




 */